sonar.projectKey=Task1Gradle
sonar.projectName=Task1Gradle
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.junit.reportPaths=build/test-results/test
sonar.sourceEncoding=UTF-8

